language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: allLP92ajqvGK3cnS9EYSVYf4yIJhNMWOQhTeWoTzgyBx/ElSpw7L8rlT51RYA3pGU/s0ZsdAcFpatm9exHYldM8N1hifMAkYBL5ifsl2leQdApCW2+W9fNDrljo1DDRdNy1EFwP32VW94vNAciIpjiKxuPdbnGysXogMywnpnc/CLxcOzvwA4exsz7GOmqtrn1qLuUNtgXi77byhDCobS7XTTTD1OHWrOyf7wYpKzgKChx2Yjk2Qdu2VL1XCRCL4+WHtz8GENV+a4PpPp2RVgQPOzINkOrbrhZ2qpTXNfN4f2ABBEHRjfWB5X5hxLino91hTfqkHJaWLzoblvWL9k66V/tKuFIUlspXRbmlauPjlWD/4oLge30qF4oFCnzWsW4O9RjbF8jRjlNhM/7YBV0hwxXY2YQWgooLw/xm2E5yifGoynEvbEF+MPGWUV1TehZ21rKXMf7iq4fpAIT4Q9gISWgFTYVsmbu0P5QVHHZmfwhZvJbRjCmWss51QykYK2lYHq5rN6b5Il0qeFdV69qqYB/8jIA2BnzT1zHnQnRYoC6YfJH+6Y0rWF7O2VrS0oVNtCuQdvL6V+T0qIgYJkHs48QIWza5yEpt/0ZTgBREGBJiK6stujkxDvxluJp8Vd43UvvjgtIXpJ1UIi72cSoTo3AQJJktf73I0DOQHAU=
  app: julie-noteful-v3a
  on:
    repo: thinkful-ei19/julie-noteful-v3a
